spring:
  application:
    name: service-client
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
        alphanumeric-ids:
          enabled: true
      client:
        config:
          default:
            connectTimeout: 1000
            readTimeout: 1000
            loggerLevel: full
resilience4j:
  circuitbreaker:
    instances:
      UserServiceClientgetAllUsers:
        slidingWindowSize: 5
        minimumNumberOfCalls: 2
        permittedNumberOfCallsInHalfOpenState: 100
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 650s
        failureRateThreshold: 10
        slidingWindowType: COUNT_BASED
        eventConsumerBufferSize: 10
        recordExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - feign.FeignException
          - java.lang.InternalError
          - java.lang.Exception
#
#
#    configs:
#      default:
#        slidingWindowSize: 5
#        minimumNumberOfCalls: 2
#        permittedNumberOfCallsInHalfOpenState: 100
#        automaticTransitionFromOpenToHalfOpenEnabled: true
#        waitDurationInOpenState: 650s
#        failureRateThreshold: 10
#        eventConsumerBufferSize: 10
#        slidingWindowType: COUNT_BASED
#        recordExceptions:
#          - java.io.IOException
#          - java.util.concurrent.TimeoutException
#          - feign.FeignException
#          - java.lang.InternalError
#          - java.lang.Exception

  retry:
    instances:
      userServiceClient:
        max-attempts: 3
        waitDuration: 1s
        retryExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - feign.FeignException
          - java.lang.InternalError
          - java.lang.Exception
          - java.net.SocketTimeoutException
      UserServiceClientsaveUser:
        max-attempts: 3
        waitDuration: 1s
        retryExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - feign.FeignException
          - java.lang.InternalError
          - java.lang.Exception
          - java.net.SocketTimeoutException
    configs:
      default:
        max-attempts: 3
        waitDuration: 1s
        retryExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - feign.FeignException
          - java.lang.InternalError
          - java.lang.Exception
          - java.net.SocketTimeoutException
    metrics:
      enabled: true
#@FeignClient(url = "http://localhost:8080")
#  public interface DemoClient {
#
#  @GetMapping("demo")
#  String getDemo();6546546546
#}
#
#  You could configure it using configuration properties by doing the following
#
#spring:
#  cloud:
#    openfeign:
#      circuitbreaker:
#        enabled: true
#        alphanumeric-ids:
#          enabled: true
#resilience4j:
#  circuitbreaker:
#    instances:
#      DemoClientgetDemo:
#        minimumNumberOfCalls: 69
#  timelimiter:
#    instances:
#      DemoClientgetDemo:
#        timeoutDuration: 10s