spring:
  application:
    name: config-server
  config:
    activate:
      on-profile: native
---
spring:
  profiles:
    active: prod
  cloud:
    config:
      server:
        git:
          uri: git@github.com:marco-antonio-bejar-villalba/POC-eureka-configserver.git
          search-paths: configurations
---
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations

