spring:
  application:
    name: config-server
  profiles:
    active: prod
---
spring:
  config:
    activate:
      on-profile: prod
  cloud:
    config:
      server:
        git:
          uri: https://github.com/marco-antonio-bejar-villalba/POC-eureka-configserver.git
          search-paths: configurations
---
spring:
  config:
    activate:
      on-profile: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations

