
spring:
  application:
    name: config-server
  profiles:
    active: native
server:
  port: 8888
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  config:
    activate:
      on-profile: prod
  cloud:
    config:
      server:
        git:
          uri: https://github.com/marco-antonio-bejar-villalba/POC-eureka-configserver.git
          search-paths: configurations
          username: ${git.user}
          password: ${git.password}
---
spring:
  config:
    activate:
      on-profile: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations

